global using FastEndpoints;
global using MediatR;
global using System.Security.Claims;
global using FluentValidation;
global using System.Text.Json.Serialization;
global using FastEndpoints.Swagger;
global using Grpc.Core;
global using Identity.API.Protos;
global using Microsoft.EntityFrameworkCore;