apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoption-service
  namespace: pncm
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: adoption-service
  template:
    metadata:
      labels:
        app: adoption-service
    spec:
      containers:
        - name: adoption-service
          image: ilkoninn/pncm-adoption:sha-140a68871c6231d10189bbf68fabc0f71d8385e1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: pncm-config
            - secretRef:
                name: pncm-secrets
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=pncm-postgres;Port=5432;Database=pncm_adoption;Username=postgres;Password=postgres;Encoding=UTF8"
            - name: Jwt__Issuer
              value: "pncm-identity"
            - name: Jwt__Audience
              value: "pncm-api"
            - name: Jwt__SecretKey
              valueFrom:
                secretKeyRef:
                  name: pncm-secrets
                  key: JWT_SECRET
            - name: Kafka__BootstrapServers
              value: "pncm-kafka:29092"
            - name: Otlp__Endpoint
              value: "http://pncm-jaeger:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: pncm-adoption
  namespace: pncm
spec:
  selector:
    app: adoption-service
  ports:
    - port: 80
      targetPort: 8080
