apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: pncm
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: ilkoninn/pncm-identity:sha-6b3ba2618b7d24728a07ade834a245b5264f36c1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: pncm-config
            - secretRef:
                name: pncm-secrets
            - secretRef:
                name: pncm-email-secrets
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=pncm-postgres;Port=5432;Database=pncm_identity;Username=postgres;Password=postgres;Encoding=UTF8"
            - name: ConnectionStrings__Redis
              value: "pncm-redis:6379"
            - name: Jwt__SecretKey
              valueFrom:
                secretKeyRef:
                  name: pncm-secrets
                  key: JWT_SECRET
            - name: Jwt__Issuer
              value: "pncm-identity"
            - name: Jwt__Audience
              value: "pncm-api"
            - name: Kafka__BootstrapServers
              value: "pncm-kafka:29092"
            - name: Otlp__Endpoint
              value: "http://pncm-jaeger:4317"
            - name: GrpcServices__MediaService
              value: "http://pncm-media:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: pncm-identity
  namespace: pncm
spec:
  selector:
    app: identity-service
  ports:
    - port: 80
      targetPort: 8080
