apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pncm-ingress
  namespace: pncm
spec:
  ingressClassName: traefik
  rules:
    - host: pncm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pncm-gateway
                port:
                  number: 80
