apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-service
  namespace: pncm
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pet-service
  template:
    metadata:
      labels:
        app: pet-service
    spec:
      containers:
        - name: pet-service
          image: ilkoninn/pncm-pet:sha-8b5967734e0805af412e0388306b2a91729e2cdd
          ports:
            - containerPort: 8080
            - containerPort: 8081
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: pncm-config
            - secretRef:
                name: pncm-secrets
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=pncm-postgres;Port=5432;Database=pncm_pet;Username=postgres;Password=postgres;Encoding=UTF8"
            - name: Jwt__Issuer
              value: "pncm-identity"
            - name: Jwt__Audience
              value: "pncm-api"
            - name: Jwt__SecretKey
              valueFrom:
                secretKeyRef:
                  name: pncm-secrets
                  key: JWT_SECRET
            - name: Otlp__Endpoint
              value: "http://pncm-jaeger:4317"
            - name: GrpcServices__MediaService
              value: "http://pncm-media:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: pncm-pet
  namespace: pncm
spec:
  selector:
    app: pet-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 8081
      targetPort: 8081
