public sealed record PetResponseDto(
    Guid Id,
    string Name,
    string Slug,
    ESpecies Species,
    string? Breed,
    int? AgeMonths,
    EGender Gender,
    EPetSize Size,
    string? Color,
    string? Description,
    bool IsVaccinated,
    bool IsNeutered,
    EPetStatus Status,
    Guid OwnerId,
    EOwnerType OwnerType,
    string? OwnerFirstName,
    string? OwnerLastName,
    string City,
    decimal? Latitude,
    decimal? Longitude,
    IEnumerable<PetPhotoResponseDto> Photos,
    DateTime CreatedAt,
    DateTime? UpdatedAt = null,
    string? PrimaryPhotoUrl = null
);